Repository bfhmea4/mea4_01_habits, pull requests merged in 2022-12, with the labels that each got.

#175 169 provide a way to login and logout
  .github/workflows/pr-labels.yaml
  ui/pages/profile.tsx
Labels: size/M

#176 filter habits
  .github/workflows/pr-labels.yaml
  mvnw
  mvnw.cmd
  src/main/kotlin/ch/bfh/habits/services/HabitService.kt
  ui/components/general/Nav.tsx
  ui/components/journalEntry/JournalDashboard.tsx
  ui/pages/_app.tsx
  ui/pages/journal.tsx
  ui/pages/profile.tsx
  ui/public/__ENV.js
Labels: size/XL

#177 Authorization and enable OpenApi docs
  .pre-commit-config.yaml
  pom.xml
  src/main/kotlin/ch/bfh/habits/config/SecurityConfiguration.kt
  src/main/kotlin/ch/bfh/habits/controllers/AuthController.kt
  src/main/kotlin/ch/bfh/habits/controllers/HabitController.kt
  src/main/kotlin/ch/bfh/habits/controllers/JournalEntryController.kt
  src/main/kotlin/ch/bfh/habits/dtos/habit/HabitEntityBuilder.kt
  src/main/kotlin/ch/bfh/habits/dtos/journalentry/JournalEntryEntityBuilder.kt
  src/main/kotlin/ch/bfh/habits/entities/Habit.kt
  src/main/kotlin/ch/bfh/habits/entities/JournalEntry.kt
  src/main/kotlin/ch/bfh/habits/filters/JwtRequestFilter.kt
  src/main/kotlin/ch/bfh/habits/repositories/HabitDAO.kt
  src/main/kotlin/ch/bfh/habits/repositories/JournalEntryDAO.kt
  src/main/kotlin/ch/bfh/habits/repositories/UserDAO.kt
  src/main/kotlin/ch/bfh/habits/services/CustomUserDetailService.kt
  src/main/kotlin/ch/bfh/habits/services/HabitService.kt
  src/main/kotlin/ch/bfh/habits/services/JournalEntryService.kt
  src/main/kotlin/ch/bfh/habits/services/UserService.kt
  src/main/kotlin/ch/bfh/habits/testdata/DatabaseLoader.kt
  src/main/kotlin/ch/bfh/habits/util/TokenProvider.kt
  src/main/resources/application.properties
  src/main/resources/db/migration/V1_0_0__Initial.sql
  src/main/resources/postman/Habits.postman_collection.json
  src/test/kotlin/ch/bfh/habits/controllers/HabitControllerTests.kt
  src/test/kotlin/ch/bfh/habits/controllers/JournalEntryControllerTests.kt
  src/test/kotlin/ch/bfh/habits/dtos/HabitEntityBuilderTests.kt
  src/test/kotlin/ch/bfh/habits/dtos/JournalEntryEntityBuilderTests.kt
Labels: size/XXL

#164 feat: add frequency in ui
  src/main/kotlin/ch/bfh/habits/dtos/habit/HabitEntityBuilder.kt
  ui/components/general/forms/Select.tsx
  ui/components/general/modals/PopUpModal.tsx
  ui/components/habits/HabitForm.tsx
  ui/lib/interfaces.ts
  ui/lib/parse.ts
Labels: size/L

#178 Change descriptions to type text
  src/main/kotlin/ch/bfh/habits/entities/Habit.kt
  src/main/kotlin/ch/bfh/habits/entities/JournalEntry.kt
  src/main/resources/db/migration/V1_0_0__Initial.sql
Labels: size/XS

#180 Change frontend after backend refactoring
  ui/components/journalEntry/JournalEntryForm.tsx
  ui/pages/index.tsx
  ui/pages/journal.tsx
Labels: size/L

#181 Tests should compile again
  src/feature-test/kotlin/ch/bfh/habits/habit/HabitCrudActor.kt
  src/feature-test/kotlin/ch/bfh/habits/habit/HabitCrudFeatureTests.kt
  src/feature-test/kotlin/ch/bfh/habits/habit/impl/WebClientBasedHabitCrudActor.kt
  src/feature-test/kotlin/ch/bfh/habits/journalentry/JournalEntryCrudActor.kt
  src/feature-test/kotlin/ch/bfh/habits/journalentry/JournalEntryCrudFeatureTests.kt
  src/feature-test/kotlin/ch/bfh/habits/journalentry/impl/WebClientBasedJournalEntryCrudActor.kt
  src/main/kotlin/ch/bfh/habits/dtos/habit/HabitListDTO.kt
  src/main/kotlin/ch/bfh/habits/dtos/journalentry/JournalEntryListDTO.kt
  src/test/kotlin/ch/bfh/habits/controllers/HabitControllerTests.kt
  src/test/kotlin/ch/bfh/habits/controllers/JournalEntryControllerTests.kt
Labels: size/L

#182 Remove mvn wrapper
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
Labels: size/XS

#184 Fix all unit tests
  src/feature-test/kotlin/ch/bfh/habits/auth/AuthCrudActor.kt
  src/feature-test/kotlin/ch/bfh/habits/auth/impl/WebClientBasedAuthCrudActor.kt
  src/feature-test/kotlin/ch/bfh/habits/habit/HabitCrudActor.kt
  src/feature-test/kotlin/ch/bfh/habits/habit/HabitCrudFeatureTests.kt
  src/feature-test/kotlin/ch/bfh/habits/habit/HabitTestConfiguration.kt
  src/feature-test/kotlin/ch/bfh/habits/habit/impl/WebClientBasedHabitCrudActor.kt
  src/feature-test/kotlin/ch/bfh/habits/journalentry/JournalEntryCrudActor.kt
  src/feature-test/kotlin/ch/bfh/habits/journalentry/JournalEntryCrudFeatureTests.kt
  src/feature-test/kotlin/ch/bfh/habits/journalentry/JournalEntryTestConfiguration.kt
  src/feature-test/kotlin/ch/bfh/habits/journalentry/impl/WebClientBasedJournalEntryCrudActor.kt
  src/main/kotlin/ch/bfh/habits/controllers/AuthController.kt
  src/main/kotlin/ch/bfh/habits/controllers/JournalEntryController.kt
  src/main/kotlin/ch/bfh/habits/filters/JwtRequestFilter.kt
  src/main/kotlin/ch/bfh/habits/services/HabitService.kt
  src/main/kotlin/ch/bfh/habits/services/JournalEntryService.kt
  src/main/kotlin/ch/bfh/habits/util/TokenProvider.kt
  src/test/kotlin/ch/bfh/habits/controllers/HabitControllerTests.kt
  src/test/kotlin/ch/bfh/habits/controllers/JournalEntryControllerTests.kt
  src/test/kotlin/ch/bfh/habits/services/HabitServiceTest.kt
  src/test/kotlin/ch/bfh/habits/services/JournalEntryServiceTest.kt
Labels: size/XL

#185 Add more tests
  src/main/kotlin/ch/bfh/habits/repositories/HabitDAO.kt
  src/main/kotlin/ch/bfh/habits/repositories/JournalEntryDAO.kt
  src/main/kotlin/ch/bfh/habits/util/TokenProvider.kt
  src/test/kotlin/ch/bfh/habits/controllers/JournalEntryControllerTests.kt
  src/test/kotlin/ch/bfh/habits/dtos/HabitEntityBuilderTests.kt
  src/test/kotlin/ch/bfh/habits/util/TokenProviderTest.kt
Labels: size/L

#186 Update readme
  README.md
  docs/architecture/frontend.md
  docs/assets/diagrams/frontend.py
  docs/features/how-to-use.md
  docs/getting-started.md
  docs/index.md
  docs/project/project-decisions.md
  docs/project/project-meetings.md
  docs/project/project-vision.md
  docs/requirements.md
Labels: size/L

#196 feat(profile): add avatar and show username
  ui/pages/profile.tsx
  ui/public/images/avatars/1.png
  ui/public/images/avatars/2.png
Labels: size/S

#197 194 feature and vision documentation
  docs/index.md
  ui/components/general/Nav.tsx
  ui/pages/info.tsx
Labels: size/M

#199 feat: Configure application with env variables
  docker-compose-m1.yaml
  docker-compose.yaml
  docs/getting-started.md
  src/main/kotlin/ch/bfh/habits/config/ConfigurationGuard.kt
  src/main/kotlin/ch/bfh/habits/config/WebConfiguration.kt
  src/main/resources/application-local.properties
  src/main/resources/application-test.properties
  src/main/resources/application.properties
Labels: size/L

#198 UI Improvements
  ui/components/general/Nav.tsx
  ui/components/general/buttons/StyledButton.tsx
  ui/components/general/forms/Select.tsx
  ui/components/habits/HabitCard.tsx
  ui/components/habits/HabitForm.tsx
  ui/components/habits/NewHabit.tsx
  ui/components/journalEntry/JournalDashboard.tsx
  ui/config/Api.ts
  ui/lib/parse.ts
  ui/next.config.js
  ui/package.json
  ui/pages/_app.tsx
  ui/pages/index.tsx
  ui/pages/info.tsx
  ui/pages/journal.tsx
  ui/pages/profile.tsx
  ui/yarn.lock
Labels: size/XL

#200 168 show a score for each habit based on the frequency goal
  ui/components/habits/HabitCard.tsx
  ui/components/habits/HabitForm.tsx
  ui/pages/info.tsx
Labels: bug, size/S
