Repository bfhmea4/mea4_01_habits, pull requests merged in 2022-11, with the labels that each got.

#91 docs: add db docs, add first draft for project documentation
  docs/getting-started.md
  docs/project/impediment-backlog.md
  docs/project/project-decisions.md
  docs/project/project-setup.md
  mkdocs.yaml
Labels: documentation

#97 add ui Dockerfile
  ui/.dockerignore
  ui/Dockerfile
  ui/app/page.tsx
Labels: enhancement

#123 The big integration
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .gitignore
  create.sql
  docker-compose.yaml
  src/main/kotlin/ch/bfh/habits/controllers/HabitController.kt
  src/main/kotlin/ch/bfh/habits/controllers/JournalEntryController.kt
  src/main/resources/db/migration/V1_0_0__Initial.sql
  ui/.env.production
  ui/.gitignore
  ui/.lintstagedrc
  ui/.prettierignore
  ui/.prettierrc
  ui/README.md
  ui/app/layout.tsx
  ui/app/page.tsx
  ui/components/Layout.tsx
  ui/components/Loading.tsx
  ui/components/alerts/Toast.tsx
  ui/components/general/Nav.tsx
  ui/components/general/buttons/StyledButton.tsx
  ui/components/general/forms/InputField.tsx
  ui/components/general/forms/TextAreaField.tsx
  ui/components/general/modals/PopUpModal.tsx
  ui/components/habits/Dashboard.tsx
  ui/components/habits/HabitCard.tsx
  ui/components/habits/HabitForm.tsx
  ui/components/habits/NewHabit.tsx
  ui/config/Api.ts
  ui/context/loadingContext.tsx
  ui/entrypoint.sh
  ui/lib/interfaces.ts
  ui/next.config.js
  ui/package-lock.json
  ui/package.json
  ui/pages/_app.tsx
  ui/pages/index.tsx
  ui/postcss.config.js
  ui/public/__ENV.js
  ui/styles/globals.css
  ui/tailwind.config.js
  ui/tsconfig.json
  ui/yarn.lock
Labels: enhancement, big boii

#126 fix: docker build & docs: update getting-started
  .github/workflows/release.yaml
  docker-compose.yaml
  docs/getting-started.md
  src/main/kotlin/ch/bfh/habits/controllers/HabitController.kt
  src/main/kotlin/ch/bfh/habits/controllers/JournalEntryController.kt
Labels: documentation

#127 fix: logo
  assets/habits_logo.png
  mkdocs.yaml
Labels: documentation

#128 fix: logo with new name
  README.md
  assets/habits_logo_original.png
  mkdocs.yaml
Labels: documentation

#130 Update user story template
  .github/ISSUE_TEMPLATE/user_story.md
  docs/project/impediment-backlog.md
  docs/project/project-setup.md
Labels: documentation

#131 Update list of scrum meetings
  docs/project/project-setup.md
Labels: documentation

#132 Update missing meeting notes
  docs/project/project-decisions.md
  docs/project/project-meetings.md
Labels: documentation

#156 151 better input validation
  build/package/habits/Dockerfile.m1
  docker-compose-m1.yaml
  src/main/kotlin/ch/bfh/habits/WebConfig.kt
  ui/components/habits/HabitForm.tsx
  ui/components/journalEntry/JournalEntryCard.tsx
  ui/components/journalEntry/JournalEntryForm.tsx
  ui/pages/journal.tsx
Labels: enhancement

#158 feat: integrate select component
  ui/components/general/Nav.tsx
  ui/components/general/forms/Select.tsx
  ui/components/habits/HabitForm.tsx
  ui/components/journalEntry/JournalEntryForm.tsx
Labels: enhancement

#159 Fix journal creation
  ui/components/journalEntry/JournalEntryCard.tsx
  ui/components/journalEntry/JournalEntryForm.tsx
  ui/lib/interfaces.ts
Labels: enhancement

#160 feat: add authentication and login form
  src/main/kotlin/ch/bfh/habits/controllers/AuthController.kt
  ui/components/general/Nav.tsx
  ui/components/general/buttons/StyledButton.tsx
  ui/components/habits/Dashboard.tsx
  ui/components/login/LoginForm.tsx
  ui/context/userContext.tsx
  ui/lib/interfaces.ts
  ui/pages/_app.tsx
  ui/pages/login.tsx
  ui/public/images/illustrations/undraw_walking_outside_re_56xo 1.svg
  ui/public/images/logo/habits_logo_original.png
Labels: enhancement

#161 fix: readme codefactor
  README.md
Labels: documentation

#162 fix: prettier and stuff
  .pre-commit-config.yaml
  ui/components/general/Nav.tsx
  ui/components/general/forms/Select.tsx
  ui/components/habits/Dashboard.tsx
  ui/components/journalEntry/JournalEntryCard.tsx
  ui/components/journalEntry/JournalEntryForm.tsx
  ui/components/login/LoginForm.tsx
  ui/context/userContext.tsx
  ui/pages/login.tsx
  ui/public/__ENV.js
Labels: documentation
