Repository bfhmea4/mea4_01_habits, pull requests merged in 2022-10, with the labels that each got.

#16 add Dockerfile for fizzbuzz
  build/package/fizzbuzz/.keep
  build/package/fizzbuzz/Dockerfile
Labels: enhancement

#19 18: improve fizzbuzz algorithm
  pkg/fizzbuzz/fizzbuzz.go
Labels: enhancement

#30 extend docker release
  .github/workflows/release.yaml
  docker-compose.yaml
Labels: enhancement

#31 improve documentation, add README.md
  README.md
  docker-compose.yaml
  docs/create-users.md
  docs/getting-started.md
  docs/images/create_normal_user.png
  docs/images/initial_admin_user.png
  docs/images/login_frontend.png
  docs/requirements.md
  mkdocs.yaml
Labels: documentation

#34 improve docs
  docs/create-users.md
  docs/getting-started.md
  mkdocs.yaml
Labels: documentation

#35 rename docker images
  .github/workflows/release.yaml
Labels: enhancement

#36 fix docker image name
  .github/workflows/release.yaml
Labels: bug

#75 dockerize application
  .github/workflows/maven.yaml
  .github/workflows/release.yaml
  README.md
  assets/README.md
  assets/habits_logo.png
  assets/habitsad_example_logo.png
  build/package/habits/Dockerfile
  build/package/habitsad/Dockerfile
  docker-compose.yaml
  docs/getting-started.md
  mkdocs.yaml
  src/main/resources/application.properties
Labels: enhancement

#82 fix: docker-compose volume configuration
  docker-compose.yaml
  docs/getting-started.md
Labels: enhancement

#92 Update gitignore
  .gitignore
Labels: enhancement

#93 54 UI list all habits
  ui/app/habits/habitcard.tsx
  ui/app/page.tsx
  ui/lib/interfaces.ts
  ui/lib/parse.ts
  ui/package.json
  ui/public/images/habits/arrow-circle.png
  ui/yarn.lock
Labels: enhancement

#95 50 UI create a habit
  ui/app/general/buttons/StyledButton.tsx
  ui/app/general/forms/InputField.tsx
  ui/app/general/forms/TextAreaField.tsx
  ui/app/general/modals/PopUpModal.tsx
  ui/app/habits/HabitForm.tsx
  ui/app/habits/NewHabit.tsx
  ui/app/habits/habitcard.tsx
  ui/app/layout.tsx
  ui/app/page.tsx
  ui/lib/design.ts
  ui/package.json
  ui/postcss.config.js
  ui/styles/globals.css
  ui/tailwind.config.js
  ui/yarn.lock
Labels: enhancement
