Repository bfhmea4/mea4_01_habits, pull requests merged in 2023-01, with the labels that each got.

#202 docs: improve structure
  docs/architecture/backend.md
  docs/architecture/overview.md
  docs/project/project-vision.md
Labels: size/S

#205 docs: remove codefactor
  README.md
  mkdocs.yaml
Labels: documentation, size/XS

#206 docs: change color to white
  mkdocs.yaml
Labels: documentation

#212 Finish documentation
  docs/project/impediment-backlog.md
  docs/project/project-decisions.md
  docs/project/project-meetings.md
Labels: size/S

#213 Adapt things for getting started
  docker-compose-m1.yaml
  docker-compose.yaml
  docs/getting-started.md
  mkdocs.yaml
  src/main/kotlin/ch/bfh/habits/config/ConfigurationGuard.kt
  src/main/resources/application-local.properties
Labels: size/M

#214 Fix docs
  docs/project/project-decisions.md
  mkdocs.yaml
Labels: documentation

#215 fix: accent
  mkdocs.yaml
Labels: size/XS

#216 fix: length of journalentries
  ui/components/habits/HabitCard.tsx
  ui/context/userContext.tsx
  ui/next.config.js
  ui/package.json
  ui/pages/_app.tsx
  ui/yarn.lock
Labels: bug, size/XXL

#217 feat: improve routing
  ui/components/Loading.tsx
  ui/components/general/Nav.tsx
Labels: enhancement, size/M

#218 Sprint 8
  README.md
  docker-compose-m1.yaml
  docker-compose.yaml
  docs/getting-started.md
  docs/project/impediment-backlog.md
  docs/project/project-decisions.md
  docs/project/project-meetings.md
  mkdocs.yaml
  src/main/kotlin/ch/bfh/habits/config/ConfigurationGuard.kt
  src/main/resources/application-local.properties
  ui/components/Loading.tsx
  ui/components/general/Nav.tsx
  ui/components/habits/HabitCard.tsx
  ui/context/userContext.tsx
  ui/next.config.js
  ui/package.json
  ui/pages/_app.tsx
  ui/yarn.lock
Labels: size/XXL

#221 Improve readme
  README.md
Labels: size/XS

#222 Merge back
  README.md
Labels: size/XS
